name: new website static content deploy

on:
  push:
    branches: [main]

permissions:
  contents: write.

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Bootstrap
        run: npm install bootstrap@5

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "smart-coder-nilesh"
          git config --global user.email "mishranilesh@gmail.com"

          git checkout --orphan gh-pages

          git rm -rf .

          cp -r build/* ./

          git add .

          git commit -m "Deploy to GitHub Pages"

          git push origin gh-pages --force
          git checkout master
